version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: beauty_salon_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: beauty_salon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma:latest
    container_name: beauty_salon_chroma
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  postgres_data:
    name: beauty_salon_postgres_data
  chroma_data:
    name: beauty_salon_chroma_data

